# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_project_templates',
                'doc_host': 'https://daniel-vainsencher.github.io',
                'git_url': 'https://github.com/daniel-vainsencher/nbdev_project_templates',
                'lib_path': 'nbdev_project_templates'},
  'syms': { 'nbdev_project_templates.definitions': { 'nbdev_project_templates.definitions.foo': ( 'API/definitions.html#foo',
                                                                                                  'nbdev_project_templates/definitions.py')}}}
