# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb 3
# Implementation hidden via tiny triangle
# Works also in RISE (alt-R) mode, but not stored
def foo(): 
    """Docstring"""
    pass

