# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/API/00_definitions.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/API/00_definitions.ipynb 3
# Implementation code-foldable (click on grey stripe left of the def)
# Works also in RISE (alt-R) mode
def foo(): 
    """Docstring for foo"""
    return 7
