# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/API/00_definitions.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/API/00_definitions.ipynb 3
# Implementation hidden via tiny triangle
# Works also in RISE (alt-R) mode, but not stored
def foo(): 
    """Docstring for foo"""
    pass

